image: Visual Studio 2019
configuration: Release

cache:
  - build

build_script:
  - cmd: set PATH=%APPVEYOR_BUILD_FOLDER%\build\__install__\lib\;C:\Qt\5.14\msvc2017_64\bin\;%PATH%
  - cmd: set CTEST_OUTPUT_ON_FAILURE=1
  - cmd: set QT_QPA_PLATFORM=offscreen
  - cmd: C:\Python38-x64\python.exe scripts\python\build.py --build_path %APPVEYOR_BUILD_FOLDER%\build --colmap_path . --boost_path C:\Libraries\boost_1_73_0 --qt_path C:\Qt\5.14\msvc2017_64 --build_type %CONFIGURATION%
#  - cmd: cmake --build %APPVEYOR_BUILD_FOLDER%\build\colmap\build --config %CONFIGURATION% --target RUN_TESTS
